# Generated by Django 4.2.1 on 2023-05-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Employees", new_name="Employee",),
    ]
